name = "farmablebackendtest"
main = "functions/api/products.ts"
compatibility_date = "2025-02-01"

[[d1_databases]]
binding = "DB"
database_name = "farmablebackendtest-db"
database_id = "6b7333cf-d729-41db-ac63-e5bef6350a7f"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
dir = "dist"

[site]
bucket = "./dist"
entry-point = "./functions"

[site.routes]
pattern = "/api/*"
script = "farmablebackendtest"