[[d1_databases]]
binding = "DB"
database_name = "farmable-database"
database_id = "6cd713c9-04f3-4edc-9569-33f7f85de808"

# Remove the build section and add these instead
main = "functions/api/products.ts"
compatibility_date = "2024-01-31"

# Add this section for Pages
[site]
bucket = "./public"
pages_build_output_dir = "public"